### ISSUE TITLE
The palette feature proposal

### ISSUE THREAD

**Issue by andrea78** [lbovet/wb0#6] opened 2021-09-24 17:29 UTC
Laurent, 
Intuitive and user-friendly UI, refined design, fast navigation. For these features I like wb0 the most.
If simplicity is important to you, one important thing is missing.
Drop-right palette as in the original WBO design.
Adding a drop-right palette, for example the 7 basic and most frequently used colors, will allow you to work faster and more conveniently. Less clicking, faster work. Then the color picker is unnecessary, because you can always use exactly the same colors quickly. Below is a visualization. Do you like it?
![Screenshot 2021-09-24 at 19-26-22 134596952-ccc563ec-e9b6-4b01-baad-bcca2379f441 png (obraz PNG, 1366×625 pikseli) — Skala ](https://user-images.githubusercontent.com/461774/134716416-189a85cb-12db-465c-a209-939d171396bf.png)

**Comment by lbovet** [comment] 2021-09-24 17:36
Why not. We could also keep the color picker as an option in the palette. Maybe some users like more color choices.
I would welcome a PR in this direction. I will not invest time myself because it is not a bug fix or a new functionality that is dramatically needed (yet).

**Comment by andrea78** [comment] 2021-09-27 20:38
I see, I will add the palette feature if only time allowing.

**Comment by lbovet** [comment] 2021-09-30 12:13
I close it, then. It is still searchable as reference

**Closed as completed** 2021-09-30 12:13 UTC
